name: Release Build

on:
  workflow_dispatch:
  workflow_call: {}
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    name: Build Game Binaries
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Normalize repository name
        id: repo_name
        run: |
          echo "name=$(echo '${{ github.repository_name }}' | tr '[:upper:]' '[:lower:]')"
          echo "name=$(echo '${{ github.repository_name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
