name: Normalize Repository Name

on:
  workflow_dispatch:
  workflow_call: {}
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    name: Normalize Repository Name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Normalize repository name
        id: repo_name
        run: |
          echo "name=$(echo '${{ github.repository_name }}' | tr '[:upper:]' '[:lower:]')"
          echo "name=$(echo '${{ github.repository_name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
