name: Run Unit Tests

permissions:
  contents: read

on:
  push: null

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --no-fail-fast --verbose
