name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --no-fail-fast --verbose
